# Filterbank config
filterbank:
  n_filters: 256
  kernel_size: 17
  stride: 1
# Network config
masknet:
  n_blocks: 3
  n_repeats: 8
  mask_act: tanh
  bn_chan: 128
  skip_chan: 128
  hid_chan: 512
kernelnet:
  k_n_layers: 0
  k_hid_size: 256
  k_out_size: 128
# Training config
training:
  loss: ld_src+ld_mix
  epochs: 200
  batch_size: 10
  num_workers: 4
  half_lr: yes
  early_stop: no
  train_limit: 1
  val_limit: 1
# Optim config
optim:
  optimizer: adam
  lr: 0.0001
  weight_decay: 0
# Data config
data:
  train_dir: data/wav8k/min200/tr/
  valid_dir: data/wav8k/min200/tr/
  task: sep_noise
  nondefault_nsrc:
  sample_rate: 8000
  mode: min
  segment_duration: 0.256
  normalize_audio: True