# Filterbank config
filterbank:
  n_filters: 512
  kernel_size: 17
  stride: 1
# Network config
masknet:
  n_blocks: 8
  n_repeats: 3
  mask_act: tanh
  bn_chan: 128
  skip_chan: 128
  hid_chan: 512
# Training config
training:
  epochs: 200
  batch_size: 8
  num_workers: 4
  half_lr: yes
  early_stop: yes
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  train_dir: data/wav8k/min/tr/
  valid_dir: data/wav8k/min/cv/
  task: sep_noise
  nondefault_nsrc:
  sample_rate: 8000
  mode: min200
  segment_duration: 0.13
